### ISSUE TITLE
Replying to a topic immediately after a previous reply causes the text box not to clear

### ISSUE THREAD

**Issue by MarcRoizman** [StratusNetwork/web#10] opened 2018-08-05 19:30 UTC
Steps to reproduce:

1) Reply to a forum thread
2) Immediately after replying, click the reply button again
3) Your previous post should be in the text box still, as though you were editing it

**Comment by amactus** [comment] 2018-10-29 13:34
Duplicate of https://github.com/StratusNetwork/issues/issues/243

**Closed as completed by amactus** 2018-10-29 13:34 UTC
